language: java
before_install:
    - wget http://dl.google.com/android/android-sdk_r22.3-linux.tgz
    - tar xzf android-sdk_r22.3-linux.tgz
    - export ANDROID_HOME=$PWD/android-sdk-linux
    - export PATH=${PATH}:${ANDROID_HOME}/tools:${ANDROID_HOME}/platform-tools
    - echo y | android update sdk --filter platform-tools,android-18,addon-google_apis-google-18,extra-android-m2repository --no-ui --force
    - ./scripts/install-maps-jar.sh
    - ./scripts/install-support-jar.sh

after_success:
    - ./scripts/install-snapshot.sh

env:
    global:
        - secure: "usDTdxYtfTy8YFRaAoUzTiu/Q/ywsUgZIN8WlDg6HH/b1ggJSMVW8NS5fiGlVCTNqa2Q5RP1ZBcqp+MtUIpUgE3+VL1UJasvuv2HVUXa7cHhSpqvZa6wAcCHzCIP09MSeoMnbdMufQYNuVEafC9VcJBSK4YvDcuJ/GgxlbksXlQ="
        - secure: "RQCEj0v524YI2EErOIUFj78zaXaOt6FYCkgVhCdKsRYtrAdXyC+uvtpTveHiibpK/ZNgVXTVdtKdxkBL9HCVn2fwY4Ex9PcegNa11HE5GRWWT7D4VzA92IWitztnLHq5lkFOx5k3mBNFJk4R9JuU6MO4m51+GS7NjD8WgB5QYpE="

