name: Copybara tests

on:
  pull_request:
    branches: [ google ]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  copybara-tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'adopt'
          java-version: 17

      - uses: gradle/actions/setup-gradle@v4

      - name: Build
        run: |
          SKIP_ERRORPRONE=true SKIP_JAVADOC=true \
          ./gradlew assemble testClasses --stacktrace

      - name: Integration tests
        run: |
          # Only run integration tests on Copybara PRs
          (cd integration_tests && \
            SKIP_ERRORPRONE=true SKIP_JAVADOC=true \
            ../gradlew test --stacktrace --continue \
            -Drobolectric.alwaysIncludeVariantMarkersInTestName=true \
            -Drobolectric.enabledSdks=34 \
            -Dorg.gradle.workers.max=2 \
            -x :integration_tests:nativegraphics:test \
            -x :integration_tests:sdkcompat:test
          )

      - name: SdkCompat tests
        run: |
          # `SdkCompat tests` is run as a separate step because it has to run on all SDK levels, and
          # the `Integration tests` step only runs on a single SDK level.
          SKIP_ERRORPRONE=true SKIP_JAVADOC=true \
          ./gradlew :integration_tests:sdkcompat:test --stacktrace --continue \
          -Drobolectric.alwaysIncludeVariantMarkersInTestName=true
