name: Graphics Tests

on:
  push:
    branches: [ master, 'robolectric-*.x' ]
    paths-ignore:
      - '**.md'

  pull_request:
    # Do not add `paths-ignore` here, this is required to be run on every PR for the `google` branch.
    branches: [ master, google ]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  graphics_tests:
    strategy:
      fail-fast: false
      matrix:
        device: [
          macos-15-intel, # Tests Mac x86_64
          macos-latest, # Tests Mac arm64
          ubuntu-latest, # Tests Linux x86_64
          windows-latest, # Tests Windows x86_64
        ]
    runs-on: ${{ matrix.device }}

    steps:
      - uses: actions/checkout@v6

      - name: Set up JDK
        uses: actions/setup-java@v5
        with:
          distribution: 'adopt'
          java-version-file: .github/.java-version

      - uses: gradle/actions/setup-gradle@v5

      - name: Show runner info
        run: uname -a

      - name: Run unit tests
        env:
          SKIP_ERRORPRONE: true
          SKIP_JAVADOC: true
        run: >
          ./gradlew
          :integration_tests:nativegraphics:testDebugUnitTest
          --stacktrace --continue
          "-Drobolectric.alwaysIncludeVariantMarkersInTestName=true"
          "-Dorg.gradle.workers.max=2"

      - name: Upload Test Results
        uses: actions/upload-artifact@v6
        if: always()
        with:
          name: test_results_${{ matrix.device }}
          path: |
            **/build/test-results/**/TEST-*.xml
            **/roborazzi/build/reports/*
            **/roborazzi/src/screenshots/*
            **/roborazzi/build/outputs/roborazzi/*
